# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cafdcd2814c171d26844324781bfde44a7beca6fc8c3b9d57dfc184c0832bd4a7b18a9dc21b8c065eb7ae40be7efee9942e039b6dbf7d67ac45cec5590c687f

test:
  secret_key_base: 8b02f5533da28336b78d98c47ccfd85ac1c21f8a98cbd12092604711d398a1836f56851a188e008757022a4048432a89a9c2a0d4688e57f31d4e66eef769f784

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
