class AddCountryRegions < ActiveRecord::Migration
  def up
    TypCountry.create(id: 360, iso: 'ID', iso3: 'IDN', fips: 'ID',country: 'Indonesia', continent:'AS', currency_code:'IDR', currency_name:'Rupiah', phone_prefix:'62', postal_code: '^(d{5})$', languages:'id,en,nl,jv', geonameid:'1643084')
  
    TypRegion.create(id: 1340, typ_country_id: 360, name: 'Aceh', timezone:'Asia/Jakarta')
	  TypRegion.create(id: 1341, typ_country_id: 360, name: 'Bali', timezone:'Asia/Ujung_Pandang')
	  TypRegion.create(id: 1342, typ_country_id: 360, name: 'Bengkulu', timezone:'Asia/Jakarta')
	  TypRegion.create(id: 1343, typ_country_id: 360, name: 'Jakarta Raya', timezone:'Asia/Jakarta')
	  TypRegion.create(id: 1344, typ_country_id: 360, name: 'Jambi', timezone:'Asia/Jakarta')
	  TypRegion.create(id: 1345, typ_country_id: 360, name: 'Jawa Barat', timezone:'Asia/Jakarta')
	  TypRegion.create(id: 1346, typ_country_id: 360, name: 'Central Java', timezone:'Asia/Jakarta')
	  TypRegion.create(id: 1347, typ_country_id: 360, name: 'East Java', timezone:'Asia/Jakarta')
	  TypRegion.create(id: 1348, typ_country_id: 360, name: 'Yogyakarta ', timezone:'Asia/Jakarta')
	  TypRegion.create(id: 1349, typ_country_id: 360, name: 'West Kalimantan', timezone:'Asia/Jakarta')
	  TypRegion.create(id: 1350, typ_country_id: 360, name: 'South Kalimantan', timezone:'Asia/Ujung_Pandang')
	  TypRegion.create(id: 1351, typ_country_id: 360, name: 'Kalimantan Tengah', timezone:'Asia/Jakarta')
	  TypRegion.create(id: 1352, typ_country_id: 360, name: 'East Kalimantan', timezone:'Asia/Ujung_Pandang')
	  TypRegion.create(id: 1353, typ_country_id: 360, name: 'Lampung', timezone:'Asia/Jakarta')
	  TypRegion.create(id: 1354, typ_country_id: 360, name: 'Nusa Tenggara Barat', timezone:'Asia/Ujung_Pandang')
	  TypRegion.create(id: 1355, typ_country_id: 360, name: 'East Nusa Tenggara', timezone:'Asia/Ujung_Pandang')
	  TypRegion.create(id: 1356, typ_country_id: 360, name: 'Central Sulawesi', timezone:'Asia/Ujung_Pandang')
	  TypRegion.create(id: 1357, typ_country_id: 360, name: 'Sulawesi Tenggara', timezone:'Asia/Ujung_Pandang')
	  TypRegion.create(id: 1358, typ_country_id: 360, name: 'Sulawesi Utara', timezone:'Asia/Ujung_Pandang')
	  TypRegion.create(id: 1359, typ_country_id: 360, name: 'West Sumatra', timezone:'Asia/Jakarta')
	  TypRegion.create(id: 1360, typ_country_id: 360, name: 'Sumatera Selatan', timezone:'Asia/Jakarta')
	  TypRegion.create(id: 1361, typ_country_id: 360, name: 'North Sumatra', timezone:'Asia/Jakarta')
	  TypRegion.create(id: 1362, typ_country_id: 360, name: 'Timor Timur', timezone:'Asia/Ujung_Pandang')
    TypRegion.create(id: 1363, typ_country_id: 360, name: 'Maluku ', timezone:'Asia/Jayapura')
    TypRegion.create(id: 1364, typ_country_id: 360, name: 'Maluku Utara', timezone:'Asia/Jayapura')
    TypRegion.create(id: 1365, typ_country_id: 360, name: 'West Java', timezone:'Asia/Jakarta')
    TypRegion.create(id: 1366, typ_country_id: 360, name: 'North Sulawesi', timezone:'Asia/Ujung_Pandang')
    TypRegion.create(id: 1367, typ_country_id: 360, name: 'South Sumatra', timezone:'Asia/Jakarta')
    TypRegion.create(id: 1368, typ_country_id: 360, name: 'Banten', timezone:'Asia/Jakarta')
    TypRegion.create(id: 1369, typ_country_id: 360, name: 'Gorontalo', timezone:'Asia/Ujung_Pandang')
    TypRegion.create(id: 1370, typ_country_id: 360, name: 'Bangka-Belitung', timezone:'Asia/Jakarta')
    TypRegion.create(id: 1371, typ_country_id: 360, name: 'Papua', timezone:'Asia/Jayapura')
    TypRegion.create(id: 1372, typ_country_id: 360, name: 'Riau', timezone:'Asia/Jakarta')
    TypRegion.create(id: 1373, typ_country_id: 360, name: 'South Sulawesi', timezone:'Asia/Ujung_Pandang')
    TypRegion.create(id: 1374, typ_country_id: 360, name: 'Irian Jaya Barat', timezone:'Asia/Jayapura')
    TypRegion.create(id: 1375, typ_country_id: 360, name: 'Riau Islands', timezone:'Asia/Jakarta')
    TypRegion.create(id: 1376, typ_country_id: 360, name: 'Sulawesi Barat', timezone:'Asia/Ujung_Pandang')
  end
end
